data:
  apply_noise: false
  chrom: chr21
  feat_type: betas
  kind: mpatch
  nan_sub: 0.5
  num_cpgs: 128
  sps: 8
  test_dataset: gtex
  test_spp: 5
  train_dataset: gtex
  train_spp: 10
exp:
  sim_seed: null
  split: donor_holdout
  test_nr: rrbs_sim
  train_nr: mcar_90
group: donor_holdout
log:
  embeds: false
  paramNorms: false
model:
  activation: relu
  arch: dcae
  batch_dim: 256
  criterion: mse
  device: cuda:0
  early_stop: true
  enc_last_activation: true
  es_delta: 0.01
  es_steps: 5
  kernel_sizes:
  - 5
  - 5
  - 5
  - 5
  - 5
  l2_penalty: 0
  last_activation: sigmoid
  learning_rate: 0.0005
  num_epochs: 100
  out_channels:
  - 32
  - 64
  - 128
  - 128
  - 256
  posn_embed: type1_concat
  stem_activation: null
  stem_bnorm: null
  stem_dict: null
  strides:
  - - 1
    - 1
  - - 1
    - 1
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 2
  use_bnorm: false
name: DH-GTEx
notes: Donor holdout run for basic MSlice model. Chr21 used.
